- libraries/Ethernet/library.properties
- libraries/OneWire/library.properties
- libraries/SD/library.properties
- libraries/TFT/library.properties
Avoid conflicts with standard libs by specifying architecture
> Specify architecture in library properties

- cores/arduino/IPAddress.cpp
- cores/arduino/IPAddress.h
- cores/arduino/WString.cpp
- cores/arduino/WString.h
- cores/arduino/new.cpp
- cores/arduino/new.h
- cores/arduino/stdlib_noniso.cpp
- variants/arduino_101/variant.h
This is needed to pass C++ validation in test suite
> Fixes to pass validation with test suite

- libraries/CurieBle/src/BleCharacteristic.cpp
- libraries/CurieBle/src/BleDescriptor.cpp
The correct way to get a String lenght is by calling String.length()
Now len field is protected so a compilation error will be triggered if accessing the field directly
> Fix BLE library String handling

- libraries/SoftwareSerial/SoftwareSerial.h
Class has virtual functions inherited from a base class, but its destructor is not virtual and not empty
> Resolving KW issue with SoftwareSerial destructor

- cores/arduino/wiring_analog.c
For all non PWM pins, the behavior of calling analogWrite() should be
logic 0 if the value is 127 or less. For values of 128 or above, the pin
should go to logic 1.
> ATLEDGE-396 Fix behavior of analogWrite() on non PWM pins

- platform.txt
while we solve the bug IDE-side, it is safe to revert using the hardcoded version number to handle the sketchUploader installation;
This solves a clash with outdeted Galileo/Edison core which tools are picked randomly (depending on json download order and java filesystem library internal ordering).
@calvinatintel
> hardcode sketchUploader version

- libraries/CurieEEPROM/src/CurieEEPROM.h
-remove leftover debug prints
-put() and get() should only support 32-bit alligned addresses
> CurieEEPROM fixes

- platform.txt
Renaming sketchUploader tool to arduino101load to avoid conflict in IDE if Galileo/Edison is installed
> ATLEDGE-491 - rename sketchUploader tool to arduino101load

- libraries/CurieTimerOne/CurieTimer.cpp
CureTimerOne library:  Routine resume() did not re-enable interrupt upon exit - bug.  Corrected.
> Jira-501: CurieTimer.resume() did not re-enable interrupt at the controller.

- libraries/Adafruit_NeoPixel/Adafruit_NeoPixel.cpp
JIRA: ATLEDGE-470
@bigdinotech, @calvinatintel, @intel-larry, @SidLeung 
please review
> Green pixel fix

- libraries/CurieTimerOne/CurieTimer.cpp
- libraries/CurieTimerOne/keywords.txt
* Fix pwmStop recognition in keywords.txt
* ATLEDGE-516 PWM does not stop using 0% duty cycle
> Fix issues in CurieTimerOne

- libraries/CurieTimerOne/CurieTimer.cpp
This fix is similar to the 0% duty-cycle fix. The interrupt was not being stopped for 100% duty-cycle condition.
> Stop interrupt when switching to 100% duty cycle

- libraries/Wire/Wire.cpp
-sends a byte of value 0 when doing an i2c bus scan
> i2c bus scan workaround

- boards.txt
- platform.txt
Reopening closed PR #126 to fix sketch size.
> Fixing sketch size calculation (text + ctors + rodata + datas

- libraries/CurieBLE/keywords.txt
- libraries/CurieBLE/src/BLEPeripheral.cpp
- libraries/CurieBLE/src/BLEPeripheral.h
Added Eddystone-URL support: added setAdvertisedServiceData() to support BLE Service Data; changed Incomplete to Complete Service UUID list code in Advertising initialization, required by Eddystone-URL protocol; added (for debugging and testing Advertising) getAdvertisingLength() and getAdvertising() to enable a Sketch to view the generated BLE Advertising packet.
This change allows an Arduino 101 to be a beacon, specifically an Eddystone-URL beacon, as used in Google's Physical Web(tm) project.  See https://google.github.io/physical-web/
> Added Eddystone-URL support

- libraries/CurieTimerOne/src/CurieTimerOne.cpp
CurieTimerOne::pwmStop() was doing a digitalWrite(pwmPin, LOW) after the kill() so unless the pin happened to be 0 the pwmPin might be left in the HIGH state causing motors or other devices to run HIGH after pwmStop(). Just removed the pwmPin = 0 from kill() and it passes all our loopback tests.
> JIRA-578 pwmStop() leaves pin HIGH

- libraries/CurieIMU/src/CurieIMU.cpp
- libraries/CurieIMU/src/CurieIMU.h
Please review this change. For all features, all functions returns a 'bool', therefore, the main function should return a bool.
The team advise that I make the change and have your review/approve it.
> Jira-560, getInterruptStatus(...) should return type of bool

- libraries/CurieI2S/examples/I2S_RxCallback/I2S_RxCallback.ino
- libraries/CurieI2S/examples/I2S_TxCallback/I2S_TxCallback.ino
- libraries/CurieI2S/keywords.txt
- libraries/CurieI2S/library.properties
- libraries/CurieI2S/src/CurieI2S.cpp
- libraries/CurieI2S/src/CurieI2S.h
- variants/arduino_101/variant.h
> CurieI2S library

- platform.txt
In order to debug with JTAG, an unstripped ELF file is needed. This change creates two ELF files: stripped and unstripped
> Retain unstripped ELF file for debugging

- libraries/SPI/src/SPI.cpp
- libraries/SPI/src/SPI.h
- libraries/SPI/src/SPI_registers.h
- variants/arduino_101/pins_arduino.h
- variants/arduino_101/variant.cpp
Add 'SPI1' instance to current SPI library, for accessing the onboard SPI flash. Additionally, tidy up the SPI library code (there is one commit for each. The only functional changes are in the first commit "Add support for SPI1 device to SPIClass").
> Add support for SPI1 device

- libraries/CurieSoftwareSerial/src/SoftwareSerial.h
-Remove #undefs from CurieSoftwareSerial Library
-Because it was braking some functionality such abs()
> Remove unnecessary #undefs

- cores/arduino/i2c.c
- cores/arduino/i2c.h
- libraries/Wire/examples/bus_scan/bus_scan.ino
- libraries/Wire/src/Wire.cpp
- system/libarc32_arduino101/drivers/i2c_priv.h
- system/libarc32_arduino101/drivers/ss_dw_i2c.c
- system/libarc32_arduino101/drivers/ss_i2c_iface.c
@linrjing @sgbihu
using read instead of write to avoid sending the extra byte when scaning I2C bus
> JIRA-560 I2C Bus Scan

- libraries/CurieBLE/examples/BatteryMonitor/BatteryMonitor.ino
- libraries/CurieBLE/examples/ButtonLED/ButtonLED.ino
- libraries/CurieBLE/examples/CallbackLED/CallbackLED.ino
- libraries/CurieBLE/examples/LED/LED.ino
- libraries/CurieIMU/examples/Accelerometer/Accelerometer.ino
- libraries/CurieIMU/examples/AccelerometerOrientation/AccelerometerOrientation.ino
- libraries/CurieIMU/examples/FreeFallDetect/FreeFallDetect.ino
- libraries/CurieIMU/examples/Gyro/Gyro.ino
- libraries/CurieIMU/examples/MotionDetect/MotionDetect.ino
- libraries/CurieIMU/examples/ShockDetect/ShockDetect.ino
- libraries/CurieIMU/examples/StepCount/StepCount.ino
- libraries/CurieIMU/examples/TapDetect/TapDetect.ino
- libraries/CurieIMU/examples/TapDoubleDetect/TapDoubleDetect.ino
- libraries/CurieIMU/examples/ZeroMotionDetect/ZeroMotionDetect.ino
- libraries/CurieTime/examples/ReadTest/ReadTest.ino
- libraries/CurieTime/examples/SetTime/SetTime.ino
@bigdinotech @calvinatintel @SidLeung ready for review, please read summary below and advise.
Summary of changes; This time, I've made the change only on example files provided by us (instead of the whole corelibs), and I've added all of the example files (4 of them were missed last time), with the following exception;
None of the files in libraries/CurieTimerOne/examples have a proper license. I'm assuming they should have the same license s the other example files-- I'll add it, unless there's a special reason for this I don't know about?
> ATLEDGE-553 Modify library examples header info

- libraries/CurieIMU/src/BMI160.cpp
This function is reading all 8 bits of RA_STEP_CONF_1 (0x7A-0x7B)
to obtain a value for min_step_buf, though this value is only
represented by the lower 3 bits; bit 4 is used as the 'enable' bit.
As a consequence, this function will read the step detection mode
incorrectly when step counting is enabled. Fix this by only reading
the lower 3 bits of RA_STEP_CONF_1.
> ATLEDGE-572: Fix getStepDetectionMode()

- cores/arduino/WString.cpp
@eriknyquist @bigdinotech @SidLeung Please review
> ATLEDGE-586: String.compareTo() does not compute the same as Uno for POS values

- cores/arduino/UARTClass.cpp
UARTClass::init() muxes out the UART pins to Arduino header pins 0/1.
Reset the mux on UARTClass::end() so that pins 0/1 can be used as GPIOs
again.
> Issue #241: make Serial1 release GPIO pins on end()

- libraries/SerialFlash/examples/RawHardwareTest/RawHardwareTest.ino
RawHardwareTest reports the 101's on-board SPI flash chip as an unknown
device. Fix this by adding the device's JEDEC ID to the example sketch.
> ATLEDGE-643: Add chip ID to SerialFlash example sketch

- cores/arduino/UARTClass.cpp
- system/libarc32_arduino101/drivers/ns16550.c
- system/libarc32_arduino101/drivers/uart.h
This is a workarround for a very subtle bug that affect the UART receiver, and that was discussed in https://github.com/01org/corelibs-arduino101/pull/259.
When the UART receiver is disconnected (with SET_PIN_MODE(17, GPIO_MUX_MODE)) for a time shorter than a line break and longer than a start bit, it interpret that as a received packet, and if data are transmitted immediatly after, they are corrupted.
This commit is a workarround for that bug, that enable the loopback feature of the UART when UART is disconnected, so the UART module does not notice it is disconnected.
A previous workarround for this bug (a forced delay after disconnection) is not needed anymore and is removed.
Here is a example code that shows how a false packet can be received with the good timing (rx and tx pins must …
> Fix UART receiver corruption when data sent after short disconnection

- libraries/CurieSMC/examples/smcTest/smcTest.ino
- libraries/CurieSMC/src/CurieSMC.cpp
-properly set flags for both cores during read() and write()
-add example sketch for CurieSMC library
> CurieSMC library fixes

- boards.txt
- platform.txt
- programmers.txt
Needs to be paired with a json which installs flashpack.
> Add flashpack to IDE

- cores/arduino/WString.cpp
- cores/arduino/WString.h
Port of https://github.com/arduino/Arduino/pull/5362.
(The spacing in `toFloat` was inconsistent previously, so also made it uniform.
> WString: add `toDouble`

- libraries/Wire/examples/bus_scan/bus_scan.ino
Improve documentation, code formatting and use LED_BUILTIN instead of 13 to control the on-board led connected to digital pin 13 of Arduino/Genuino 101
> Update bus_scan.ino sketch of Wire library

- libraries/CurieMailbox/examples/SharedCounter/SharedCounter.ino
- libraries/CurieMailbox/examples/String/String.ino
Mailbox X86 examples now have CDC-ACM support
@calvinatintel @bigdinotech please review.
https://github.com/01org/CODK-M-X86-Samples/pull/17 must be merged before this one.
> CurieMailbox examples: use Serial instead of Serial1

- libraries/CurieMailbox/src/CurieMailbox.cpp
- libraries/CurieMailbox/src/CurieMailbox.h
- libraries/CurieMailbox/src/CurieMailboxMsg.h
Arduino users are more comfortable with ints. Use ints instead of
'unsigned' or 'uint*', and the extra check for non-negativity, wherever
possible.
@bigdinotech @SidLeung please review.
> CurieMailbox: Use ints for public function parameters

- libraries/CurieMailbox/examples/SharedCounter/Makefile
- libraries/CurieMailbox/examples/String/Makefile
This allows the examples to be used immediately in CODK-M, without
editing any Makefiles.
@bigdinotech @SidLeung @calvinatintel please review
> Add CODK Makefile to CurieMailbox examples

- cores/arduino/Arduino.h
- cores/arduino/wiring_analog.c
- cores/arduino/wiring_digital.c
- libraries/CurieI2S/src/CurieI2S.cpp
- libraries/SPI/src/SPI.cpp
This has the effect of moving g_APinDescription out of .data (SRAM),
and into .rodata (flash).
Pros:
sketches now have an additional 1160 bytes of SRAM available
Cons:
state of pins is no longer tracked; e.g. when calling digitalWrite,
the full configuration is done each time. See changes in wiring_digital.c
and wiring_analog.c for details. There is inevitably a performance impact
for digitalRead/Write & analogRead/Write, though it is unlikely to be a
noticable one.
@calvinatintel @bigdinotech @SidLeung @russmcinnis @noelpaz please review.
**Do not merge until it is explicitly requested**
> Make g_APinDescription const

- platform.txt
The current save mechanism breaks when a user has deleted system32 from PATH environment variable. Comment out the copying so that it won't break for such users, but do not delete so that advanced users can use the unstripped elfs to debug.
> Don't save unstripped elf for debugging

- libraries/CurieSoftwareSerial/examples/SoftwareSerialExample/SoftwareSerialExample.ino
- libraries/CurieTime/examples/ReadTest/ReadTest.ino
- libraries/CurieTime/examples/SetTime/SetTime.ino
- libraries/CurieTimerOne/examples/CurieTimer1BlinkSpeed/CurieTimer1BlinkSpeed.ino
- libraries/CurieTimerOne/examples/CurieTimer1Interrupt/CurieTimer1Interrupt.ino
- libraries/SPI/examples/BarometricPressureSensor/BarometricPressureSensor.ino
- libraries/SerialFlash/examples/CopyFromSerial/CopyFromSerial.ino
Pull request to improve sketches of CurieSoftwareSerial, CurieTime, CurieTimerOne, SPI and SerialFlash libraries that use Serial communication.
Despite the modified sketches belong to different libraries, I have made a single pull request since, for all the improved sketches, the main intent is to add more documentation and the line 
`while (!Serial); ` in order to wait for the Serial port to open because, in the modified sketches, Serial communication is managed through the virtual serial port (over USB) using the object _Serial_
Best regards
> Improve sketches of different libraries that use Serial communication

- libraries/CurieI2S/src/CurieI2SDMA.cpp
The g_APinDesctiption is now 'const', so cannot be modified.
@bigdinotech please review
> I2SDMA: Do not modify g_APinDescription

- libraries/CurieIMU/src/BMI160.cpp
- libraries/CurieIMU/src/BMI160.h
accelDataReady() and gyroDataReady() read the drdy_acc and drdy_gyr
bits, respectively, of the BMI160's sensor status register. This removes
the burden of syncronising sensor reads from the user.
(adapted from descampsa/corelibs-arduino101@773a800)
@bigdinotech @calvinatintel @SidLeung please review.
Don't merge this. I'm gonna do some testing and I'll merge it when that's done.
> Add functions to check if new IMU data is available

- cores/arduino/Arduino.h
- cores/arduino/dccm/dccm_alloc.c
- cores/arduino/dccm/dccm_alloc.h
-expose dccm area giving the user an extra 8k of memory
-simple implementation of a malloc like function for dccm memory area
> Expose dccm area

- cores/arduino/RingBuffer.cpp
- cores/arduino/RingBuffer.h
-this buffer is used by the uart. Moving it into the DCCM area would
save us 128 bytes of SRAM
> Allocate RingBuffer buffer into DCCM area

- libraries/CurieTime/src/CurieTime.cpp
This fixes 6 KW issues.
@SidLeung @bigdinotech please review.
> CurieTime.cpp: check gmtime() return pointer for NULL-ness

- README.md
- libraries/CurieBLE/README.md
@SidLeung this was added with the big BLE commit (ae78b162), but I'm not sure if we need it in the corelibs README. What do you think?
> README.md: remove Serial1 debug information

- libraries/CurieIMU/src/CurieIMU.cpp
This is unnecessary- nothing else is contending for access to this
particular SPI controller
@SidLeung @bigdinotech please review
@noelpaz @russmcinnis please test
> CurieIMU.cpp: Don't lock interrupts for SPI transfers

- libraries/CurieMailbox/examples/String/String.ino
- libraries/CurieMailbox/src/CurieMailbox.cpp
- libraries/CurieMailbox/src/CurieMailbox.h
Also, add public 'numChannels' constant to CurieMailbox class, so all
channels can be easily iterated over.
These changes allow us to demonstrate how to iterate over all the mailbox channels in the String.ino example
@bigdinotech @SidLeung please review
> CurieMailbox/examples/String.ino: receive on all channels

- variants/arduino_101/variant.cpp
- variants/arduino_101/variant.h
-needed to make sure that the RTC scaling is consitent with the factory
firmware and CODK-M based firmware
> Ensure RTC clock scaling is set to 1Hz

- cores/arduino/Arduino.h
- cores/arduino/wiring_analog.c
- cores/arduino/wiring_digital.c
- libraries/CurieSoftwareSerial/src/SoftwareSerial.cpp
- libraries/SPI/src/SPI.cpp
- variants/arduino_101/variant.cpp
-check and make sure that the pin is in GPIO_MUX_MODE when doing a
digitalWrite()
-this has a slight performance impact of digitalWrite
-it also comsumes an extra byte in SRAM per pin
-it does however give us the ability to track the muxing state of each
pin
> check mux mode when using digitalWrite

- libraries/CurieI2S/examples/I2SDMA_RXCallBack/I2SDMA_RXCallBack.ino
- libraries/CurieI2S/examples/I2SDMA_TXCallBack/I2SDMA_TXCallBack.ino
- libraries/CurieI2S/examples/I2S_RxCallback/I2S_RxCallback.ino
The latest BLE library consumes more heap space that causes these sketches ran out of heap space for their temporary
buffers.  For now, the size of the tempporary is reduced.  For the near future, there are 3 improvements to address
this issue.  The BLE library will be making use of the DCCM memory instead of heap.  The I2S library buffering space
is going to the DCCM memory too.  The heap space will be increased to maximize the usage of the entire SRAM sapce.
> I2S example sketches failed compliation, Jira 786.

- libraries/CurieIMU/src/CurieIMU.cpp
This ensures that "read[Accelerometer/Gyro]Scaled()" will work as
expected even if a range has not been explicitly set using the API
@russmcinnis to verify
> CurieIMU.cpp: initialize saved accel/gyro ranges in begin()

- libraries/MemoryFree/README.md
- libraries/MemoryFree/examples/freeMemory/freeMemory.ino
- libraries/MemoryFree/keywords.txt
- libraries/MemoryFree/library.properties
- libraries/MemoryFree/src/MemoryFree.cpp
- libraries/MemoryFree/src/MemoryFree.h
This is the MemoryFree libary from
http://playground.arduino.cc/code/AvailableMemory, rewritten specifically
for Arduino 101 and tinyTILE. It provides some functions for querying
available stack & heap space.
> Add new library MemoryFree

- libraries/EEPROM/src/EEPROM.cpp
- libraries/EEPROM/src/EEPROM.h
This fixes the issue report by a user in https://github.com/01org/corelibs-arduino101/issues/422
> EEPROM library: move function definitions into separate .cpp files

- libraries/CurieBLE/src/BLEDevice.h
- libraries/CurieBLE/src/BLEPeripheral.cpp
- libraries/CurieBLE/src/internal/BLEDeviceManager.cpp
- libraries/CurieBLE/src/internal/BLEProfileManager.cpp
1. The BLEStream object adds profile when boot but the HW doesn't be
initialized and makes APP crash.
2. Change the BLE initial process not depend on HW. Buffer the
attributes if HW not initialized.
3. Changed files
libraries/CurieBLE/src/BLEDevice.h - expose constructor
libraries/CurieBLE/src/BLEPeripheral.cpp - not call HW init function
libraries/CurieBLE/src/internal/BLEDeviceManager.cpp - change init order
libraries/CurieBLE/src/internal/BLEProfileManager.cpp - change constructor
> Jira 791: Sketch crash using both Firmata and BLE library, git #377

- libraries/EEPROM/src/EEPROM.cpp
<EEPROM.h> works in the Arduino IDE,  but it's not actually in a system
include location so it makes non-IDE (i.e. Klocwork) builds fail
> EEPROM.cpp: Use double quotes for include file

- variants/arduino_101/linker_scripts/flash.ld
The end of the .data section in flash must be explicitly word-aligned, otherwise
corruption can occur in a .data section that happens to contain non-word aligned
data.
Additionally, the symbols __data_ram_end and __data_rom_start should
really be inside a section (instead of just floating around).
It is functionally equivalent, however it makes the linker script much easier
to understand!
EDIT: @bigdinotech I was wrong, probably shouldn't have moved the symbols inside input sections.
https://sourceware.org/binutils/docs/ld/Location-Counter.html
"... Note: . actually refers to the byte offset from the start of the current containing object. Normally this is the SECTIONS statement, whose start address is 0, hence . can be used as an absolute address. If . is used inside a section …
> flash.ld: fix mis-aligned .data section

- libraries/CurieBLE/src/internal/BLECharacteristicImp.cpp
Issue:
-  Created Characteristic failed to reflect the initialized
value.
Root cause:
-  During initialization, the length field was incorrectly
skipped over.
> Jira 804 BLE Characteristic initialization issue, git 366

- libraries/CurieIMU/keywords.txt
- libraries/CurieIMU/src/BMI160.cpp
- libraries/CurieIMU/src/BMI160.h
- libraries/CurieIMU/src/CurieIMU.cpp
- libraries/CurieIMU/src/CurieIMU.h
This method is a bit more flexible. There is a version with no
parameters, which will return true if all enabled sensors have new
data. There is one overload, that takes a single 'flags' parameter,
which returns true if all enabled *and* selected sensors have new data.
Sensors are selectable through pre-defined bit flags. For example;
CurieIMU.dataReady() : this will return true if both the accel and gyro
are enabled, and both have new data ready.
CurieIMU.dataReady(ACCEL | GYRO) : this will return true if both the
accel and gyro have new data ready (if one of the passed sensors is not
enabled, it is ignored and the function will behave as if that sensor was not
specified)
CurieIMU.dataReady(GYRO) : this will return true if the gyro is
enabled and has new data ready. …
> Use single dataReady() method, instead of accelDataReady/gyroDataReady

- libraries/CurieBLE/src/BLECharacteristic.cpp
- libraries/CurieBLE/src/BLECharacteristic.h
- libraries/CurieBLE/src/internal/BLECallbacks.cpp
- libraries/CurieBLE/src/internal/BLECharacteristicImp.cpp
- libraries/CurieBLE/src/internal/BLECharacteristicImp.h
Mods:
1. Add an input parameter to BLECharacteristic::read() for blocking
call selection.
2. By default, read() is a blocking call.
File changes:
1. libraries/CurieBLE/src/BLECharacteristic.cpp:
- Method read() added blocking selection.
2. libraries/CurieBLE/src/BLECharacteristic.h:
- Prototype for read(), default is blocking.
3. libraries/CurieBLE/src/internal/BLECallbacks.cpp:
- Added parameter checking in profile_read_rsp_process().
4. libraries/CurieBLE/src/internal/BLECharacteristicImp.cpp
- The implementation of read() added waiting for resp if
blocking is selected.
5. libraries/CurieBLE/src/internal/BLECharacteristicImp.h:
- prototyping.
> Jira 795, read() is blocking selectable, git 383

- libraries/CurieBLE/src/BLEPeripheral.cpp
Root casue:
- The stack need use connected device to get the state.
- The current code used local address to get the link and get an error.
Code mods:
1. BLEPeripheral.cpp:
- Use central's address to get connection state.
> Jira 857, BLEPeripheral::connected() always returns false, git 444

- libraries/CurieBLE/src/BLECharacteristic.cpp
Root Cause:
Need to restart advertising after setting the broadcast option
in Characteristic.  Otherwise, broadcasting would not take
effect.
Code mods:
1. libraries/CurieBLE/src/BLECharacteristic.cpp:
- At the processing of the Boardcast option in the
characteristic, stop and restart advertising if advertising
has already started.
> Jira 832 Sketch cannot exercise BLE broadcast, git 420

- cores/arduino/RingBuffer.h
- cores/arduino/UARTClass.cpp
- system/libarc32_arduino101/drivers/ns16550.c
Root causes:
1. The uart_fifo_fill doesn't check the FIFO's length
and failed to send out all data.
2. Check the FIFO status register before write data
in FIFO.
3. Ring buffer pointer variables are not volatile and
polling mechanism failed to examine the actual
pointer value being update by foreground task.
File changes:
1. RingBuffer.h:  Make pointer as volatile.
2. UARTClass.cpp:  Added checking of FIFO size for
data Tx.
3. ns16550.c:  Added routines to h/w status register
checking.
> Jira 842 UART improvement, PR 266, broke BLE interface.

- libraries/CurieBLE/src/BLECommon.h
- libraries/CurieBLE/src/internal/BLEDeviceManager.cpp
- libraries/CurieBLE/src/internal/BLEDeviceManager.h
New feature:
- Request from Arduino to make our Central BLE library to
scan Peripheral similar to an Apple device.
- When filter is set, advertisement from a Peripheral will
only show up once (until scan is stop and start again) with
the available() call.  Otherwise, a Peripheral will appear
as often as the Central can detect its advertisement.
- Unlike an Apple device, the 101 operates under memory
constraints.  Thus, the maximum number of filter entries
is limited to 20.  In other words, if ther are more than
20 Peripherals, the filter will NOT be able to filter out
all the advertisement all the time.  A Peripherla WILL
show up multiple times when available() is called.
Code mods:
1. BLECommon.h:
- Definition of the filter entries size.
2. BLEDeviceManager.cpp:
- Peripheral filtering …
> Jira 802, BLE Central scan() to filter Peripheral adv, git #369

- libraries/CurieBLE/src/BLECharacteristic.cpp
- libraries/CurieBLE/src/BLECharacteristic.h
Feature added:
- This is directly pulled from Arduino community PR #210.
Overloading the setValue() method to take in a string
as the only input parameter, instead of a pointer
and its size.
> Jira 867, BLE setValue(), add support for strings, git #210

- libraries/CurieBLE/examples/central/peripheral_explorer/peripheral_explorer.ino
- libraries/CurieBLE/src/BLECharacteristic.cpp
- libraries/CurieBLE/src/BLEDescriptor.cpp
- libraries/CurieBLE/src/BLEDescriptor.h
- libraries/CurieBLE/src/BLEDevice.h
- libraries/CurieBLE/src/internal/BLECallbacks.cpp
- libraries/CurieBLE/src/internal/BLECallbacks.h
- libraries/CurieBLE/src/internal/BLECharacteristicImp.cpp
- libraries/CurieBLE/src/internal/BLECharacteristicImp.h
- libraries/CurieBLE/src/internal/BLEDescriptorImp.cpp
- libraries/CurieBLE/src/internal/BLEDescriptorImp.h
- libraries/CurieBLE/src/internal/BLEProfileManager.cpp
- libraries/CurieBLE/src/internal/BLEProfileManager.h
- libraries/CurieBLE/src/internal/BLEServiceImp.cpp
- libraries/CurieBLE/src/internal/BLEServiceImp.h
Feature added:
For Central mode, added the support for processing
BLE descriptor from a connected Peripheral.  Enable
the user sketch to access to descriptor value,
length info.
Code modifications:
1. peripheral_explorer.ino:
- Example sketch with added descriptor processing.
2. BLECharacteristic.cpp:
- Bug fixed in handling multi-descriptors.
3. BLEDescriptor.cpp:
- For constructors, added initialization of
descriptor storage and info.
- For copy constructor and assignment, take into
the account of descripter value and info.
- Added API's for readning and returning descriptor
info, eg. value, size.
4. BLEDescriptor.h:
- Prototyping.
5. BLEDevice.h:
- Added descriptor storage declaration.
6. BLECallbacks.cpp:
- Added call back event for decriptor arrival.
7. BLECallbacks.h:
- Prototyping. …
> Jira 859. Support BLE descriptor processing.

- libraries/CurieBLE/src/BLEDevice.cpp
- libraries/CurieBLE/src/BLEDevice.h
- libraries/CurieBLE/src/internal/BLEDeviceManager.cpp
- libraries/CurieBLE/src/internal/BLEDeviceManager.h
Added feature:
- In Central mode, the BLE library should enumerate Peripheral
that are non-connectable (eg beacon).
Code Mods:
1. BLEDevice.cpp:
- Add the call to get Manufacturer Data info from a
Peripheral.  Non-connectable device may only broadcast
this info.
2. BLEDevice.h:
- Prototyping.
3. BLEDeviceManager.cpp:
- Delete the filter about non-connectable advertisement.
- Added APIs, hasManufacturerData(), setManufacturerData(),
hasManufacturerData(), to gain access to adv info
of non-connectable Peripherals.
> Jira 836, Enumerate non connectable Peripherals in Central scan

- libraries/CurieBLE/src/internal/BLECallbacks.cpp
Root cause:
- Upon processing the write event, The received user data
was casted incorrectly using the base class.  Resulted
in using an incorrect offset that caused memcpy to
use incorrect address and length.
Code Mods:
1. BLECallbacks.cpp:
Adjust the typecast order, from base class to child
class in profile_longwrite_process() and
profile_longflush_process().
> Jira 868, BLE Peripheral stack crash with long write, git456

- libraries/CurieBLE/examples/central/sensortag_button/sensortag_button.ino
Feature added:
- Since the BLE library now support the Scan
Response Data processing, update the sketch
to look for the sensorTag localName instead
of its specific unit address.
Cod mods:
1. sensortag_button.ino:
- Replace MAC address comparison with localName
string comparison.
> Jira 870, Change sensortag_button.ino to use localName

- libraries/CurieSerialFlash/examples/CopyFromSerial/CopyFromSerial.ino
- libraries/CurieSerialFlash/examples/EraseEverything/EraseEverything.ino
- libraries/CurieSerialFlash/examples/FileWrite/FileWrite.ino
- libraries/CurieSerialFlash/examples/ListFiles/ListFiles.ino
- libraries/CurieSerialFlash/examples/RawHardwareTest/RawHardwareTest.ino
The current comments in the CurieSerialFlash examples has the library manager shortcut and the user will be downloading the versions 1.0 to 4.0, but these versions will not work with these examples and compilation fails. The user instead should be instructed to get the current working library version from github at https://github.com/PaulStoffregen/SerialFlash
> Modify comments to point to Paul Stoffregen's Serial Flash library

- libraries/CurieBLE/src/BLECharacteristic.cpp
Resolves #366.
As outlined in the sketch provided in https://github.com/01org/corelibs-arduino101/issues/366#issue-198057880.
The initial value of 0x00 that was set by the type characteristic was dropped because it has not been associated with a service yet via `addCharacteristic(...)`. This change stores the value internally like the `BLECharacteristic(const char* uuid, unsigned char properties, const char* value)` constructor path.
> CurieBLE: Set characteristic value internally if it not associated with a service yet

- libraries/CurieBLE/src/internal/BLEDescriptorImp.cpp
Feature requested:
To make the reading of the Descriptor of a BLE Characteristic a blocking read method.  The mechanism is similar to the the Characteristic read method.  However, for Descriptor read(), it is always a blocking read.
Code Mods:
1.  libraries/CurieBLE/src/internal/BLEDescriptorImp.cpp:
-  Added a flag for the Descriptor read completion event to set in foreground.
-  Check on the Descriptor read completion event in the background as an exit condition for the read method.
> Jira 890, Allow BLE Descriptor reading to be blocking, git 478

- libraries/CurieBLE/src/internal/BLECharacteristicImp.cpp
Fixes https://github.com/01org/corelibs-arduino101/issues/385.
> CurieBLE: Correct | to &, and swap order of write vs write without response

- libraries/CurieBLE/src/internal/BLEDeviceManager.cpp
- libraries/CurieBLE/src/internal/BLEDeviceManager.h
Root cause:
1. The buffer doesn't cleared. The scanned data is not the latest.
Changed files:
BLEDeviceManager.cpp
a. Clear the buffered data when start scan.
b. Invalid scan response when buffer timeout or disconnected.
> Fix Jira876 BLE scanForName() device from previous scan is picked up

- libraries/CurieBLE/src/BLEDevice.cpp
- libraries/CurieBLE/src/BLEDevice.h
- libraries/CurieBLE/src/internal/BLEDeviceManager.cpp
- libraries/CurieBLE/src/internal/BLEDeviceManager.h
Bug fixed:
This feature was implemented in PR #457, merged, and released
in Deneb.RC1.  However, it was discovered that the logic was
inverted and was report as Git issue #476.  BLE scan() and
input parameter withDuplicates is true means reporting all
Peripherals detected regardless how many times it was reported.
Code mods:
1.  libraries/CurieBLE/src/BLEDevice.cpp:
- In startScan, calls the correct routine to scan for all
Peripherals if withDuplicates is true.  Otherwise,
just scan for new ones.
2.  libraries/CurieBLE/src/BLEDevice.h:
- Prototyping.
3.  libraries/CurieBLE/src/internal/BLEDeviceManager.h,
libraries/CurieBLE/src/internal/BLEDeviceManager.cpp
- Modified header comment to reflect the input parameter
withDuplictes correct meaning.
- Default the input parameter, …
> Jira 896, BLE scan withDuplicates logic inversion, git 476

- libraries/CurieBLE/examples/peripheral/BatteryMonitor/BatteryMonitor.ino
As it has been moved to the test folder for now as part of #375. I forgot to remove this comment.
@SidLeung please make sure this change is included in Deneb.
> Remove comment about BatteryMonitor_Central sketch

- libraries/CurieBLE/examples/central/peripheral_explorer/peripheral_explorer.ino
Removes delays from `peripheral_explorer.ino` example as discussed in https://github.com/01org/corelibs-arduino101/issues/478#issuecomment-288226373.
@SidLeung please include in Deneb.
> Remove unnecessary delays from peripheral explorer example

- libraries/CurieBLE/src/internal/BLEDeviceManager.cpp
- libraries/CurieBLE/src/internal/BLEDeviceManager.h
This change waits for a scan response from the peripheral before reporting it to the user.
This is a proposal to fix https://github.com/01org/corelibs-arduino101/issues/497 and https://github.com/01org/corelibs-arduino101/issues/370#issuecomment-289112547.
The downside is that devices that don't respond to scan responses will be ignored.
@SidLeung please consider this for the Deneb release.
> Wait for scan response before reporting discovered peripheral

- libraries/CurieBLE/keywords.txt
In this way CurieBLE is highlighted as all the Arduino .h are
> Added missing keyword

- scripts/create_dfu_udev_rule
Solves https://github.com/01org/corelibs-arduino101/issues/512
Change the documentation accordingly on https://www.arduino.cc/en/guide/arduino101 and http://forum.arduino.cc/index.php?topic=377080.0
> Move create_dfu_udev_rule from loader to core

- variants/arduino_101/linker_scripts/flash.ld
-increase SRAM to 40K
-change SRAM start address
-increase heap size to 16K
-this change is needed for BLE scan for SensorTag
-requires firmware update on x86 side
> Change SRAM mapping and increase SRAM allocated to ARC core

- libraries/CurieBLE/src/BLEDevice.cpp
- libraries/CurieBLE/src/internal/BLEDeviceManager.cpp
Also fixed Jira 839
1. Stop scan, advertising and disconnect the connected devices when call end
Changed files
BLEDeviceManager.cpp - do the real action
BLEDevice.cpp - only local BLE device call the real end
> Fix Jira 864 After BLE.end() a peripheral is still showing up in scans

- cores/arduino/stdlib_noniso.cpp
This is a nasty one. Rounding up the passed float/double to the specified presicion must be the
*very first* thing we do, before doing anything else with that value
(In this case, the issue was cause by digitsBe4Decimal() returning an
incorrect value, because it was being called before passed value was
rounded up).
The result of this error can be seen by attempting to print a float/double value which equals **any power of 10, minus 0.001**, for example 9.999, 99.999, 999.999, etc. Before this commit, calls to Serial.print with such a value will hang indefinitely.
> stdlib_noniso.cpp: fix another rounding error in dtostrf

- cores/arduino/stdlib_noniso.cpp
If we are working with a negative number, then *adding* the rounding
onto the number has the opposite to the intended effect. Need to check
if the number is negative, and if so, subtract the rounding instead of
adding.
It may appear that a cleaner solution to this is to simply move the
"handle negative numbers" block (starting on what is now line 222)
before the "round up to the precision" block (starting on what is now
line 202). However, I don't think this will work without a substantial
re-design of this function, for the following reasons;
Any leading padding must be added before handling a negative number
(adding the '-' char. to output, and then flipping the number's sign for
calculations). And in order to add the right amount of padding, we must run
digitsBe4Decimal first, and in …
> stdlib_noniso.cpp: dtostrf(), subtract rounding if number is negative

- cores/arduino/mailbox.cpp
- cores/arduino/mailbox.h
- variants/arduino_101/variant.cpp
This allows the mailbox to be used for Serial (instead of polling shared
memory). The CurieMailbox library, in the codk-m-corelibs branch, will
not require any API changes, but will now just be a thin wrapper around
the methods in mailbox.cpp
@bigdinotech, look at mailbox.h to see the functions available to you.
use channel 7 for serial (e.g. `mailbox_register(7, callback);`)
> Add IPM (Inter-Processor-Mailbox) driver to cores/arduino

- libraries/CurieSoftwareSerial/src/SoftwareSerial.cpp
-set pinMode for RX and TX pins inside of begin instead of the
constructor
> SoftwareSerial regression fix

- cores/arduino/CDCSerialClass.cpp
- cores/arduino/CDCSerialClass.h
- cores/arduino/Print.h
- cores/arduino/mailbox.h
-use the IPM instead of shared memory for passing data between ARC
and x86 cores for cdc-acm.
> Use IPM for cdc-acm

- libraries/CurieBLE/keywords.txt
- libraries/CurieIMU/keywords.txt
- libraries/CuriePowerManagement/keywords.txt
- libraries/CurieTimerOne/keywords.txt
- libraries/SPI/keywords.txt
The Arduino IDE requires the use of a tab separator between the name and identifier. Without this tab the keyword is not highlighted.
Reference: https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#keywords
> Use correct separator in keywords.txt

- cores/arduino/CDCSerialClass.cpp
- cores/arduino/CDCSerialClass.h
-set a baud rate limit for cdc-acm due to the limitation of Inter Processor Mailbox
> Set a baud rate limit for cdc-acm internally

- libraries/CurieBLE/examples/Peripheral/ButtonLED/ButtonLED.ino
- libraries/CurieI2S/examples/I2SDMA_TXCallBack/I2SDMA_TXCallBack.ino
- libraries/CurieIMU/examples/FreeFallDetect/FreeFallDetect.ino
- libraries/CurieIMU/examples/MotionDetect/MotionDetect.ino
- libraries/CurieIMU/examples/RawImuDataSerial/RawImuDataSerial.ino
- libraries/CurieIMU/examples/ShockDetect/ShockDetect.ino
- libraries/CurieIMU/examples/StepCount/StepCount.ino
- libraries/CurieIMU/examples/ZeroMotionDetect/ZeroMotionDetect.ino
- libraries/Wire/examples/bus_scan/bus_scan.ino
This is part of a move to encourage use of the standard `bool` type over Arduino's non-standard `boolean` type alias.
As approved by cmaglie: https://github.com/arduino/Arduino/issues/6657#issuecomment-355597633
> Replace boolean type with bool in examples
