cores/arduino/wiring.h, libraries/SoftwareSerial/SoftwareSerial.cpp, libraries/SoftwareSerial/SoftwareSerial.h, libraries/SoftwareSerial/examples/SoftwareSerialExample/SoftwareSerialExample.ino, libraries/SoftwareSerial/examples/TwoPortReceive/TwoPortReceive.ino, libraries/SoftwareSerial/keywords.txt, libraries/SoftwareSerial/library.properties
Port of SoftwareSerial Library for Arduino101
Tx works up to 384000 bps
Rx works up to 57600 bps
=> ATLEDGE-184 SoftwareSerial Library

libraries/CurieRTC/CurieRTC.cpp, libraries/CurieRTC/CurieRTC.h, libraries/CurieRTC/examples/ReadTest/ReadTest.ino, libraries/CurieRTC/examples/SetTime/SetTime.ino, libraries/CurieRTC/readme.txt, libraries/Time/DateStrings.cpp, libraries/Time/Readme.txt, libraries/Time/Time.cpp, libraries/Time/Time.h, libraries/Time/examples/Processing/SyncArduinoClock/SyncArduinoClock.pde, libraries/Time/examples/Processing/SyncArduinoClock/readme.txt, libraries/Time/examples/TimeArduinoDue/TimeArduinoDue.ino, libraries/Time/examples/TimeCurieRTC/TimeCurieRTC.ino, libraries/Time/examples/TimeCurieRTCLog/TimeCurieRTCLog.ino, libraries/Time/examples/TimeCurieRTCSet/TimeCurieRTCSet.ino, libraries/Time/examples/TimeGPS/TimeGPS.ino, libraries/Time/examples/TimeNTP/TimeNTP.ino, libraries/Time/examples/TimeNTP_ESP8266WiFi/TimeNTP_ESP8266WiFi.ino, libraries/Time/examples/TimeRTC/TimeRTC.pde, libraries/Time/examples/TimeRTCLog/TimeRTCLog.pde, libraries/Time/examples/TimeRTCSet/TimeRTCSet.ino, libraries/Time/examples/TimeSerial/TimeSerial.ino, libraries/Time/examples/TimeSerialDateStrings/TimeSerialDateStrings.ino, libraries/Time/examples/TimeTeensy3/TimeTeensy3.ino, libraries/Time/keywords.txt, libraries/Time/library.json, libraries/Time/library.properties
Initial implementation of the CurieRTC library for the built-in RTC
Includes the Time library plus 3 new examples for the Arduino101
=> ATLEDGE-229 CurieRTC and Time Library

cores/arduino/Arduino.h
@bigdinotech @kmsywula @intel-larry @SidLeung Please review
=> Add error message if using IDE 1.6.6

platform.txt
@intel-larry @calvinatintel 
This change should suppress all of the lines from a script being printed.
To have even better user experience we can jump into cluploadArduino101 script and there we can control amount of stuff being printed based on selection in preferences menu (ticked/unticked upload box).
Needs testing on MAC/Linux/Windows before merging.
=> ATLEDGE-455 verbose/quiet selection for upload

libraries/CurieSoftwareSerial/SoftwareSerial.cpp, libraries/CurieSoftwareSerial/SoftwareSerial.h, libraries/CurieSoftwareSerial/examples/SoftwareSerialExample/SoftwareSerialExample.ino
Minor improvements to SoftwareSerial library
=> Atledge-184 Minor improvements to SoftwareSerial library

libraries/CurieSoftwareSerial/SoftwareSerial.cpp, libraries/CurieSoftwareSerial/SoftwareSerial.h
Fixed some limitations for Rx on SOC_GPIO pins.
Rx should now be functional on all pins except pin 13.
=> ATLEDGE-442 Fix some SoftwareSerial Rx limitations

platform.txt
Make changes to platform.txt to allow exporting compiled binary as a
.hex
=> ATLEDGE-423 Export compiled binary

libraries/SD/examples/CardInfo/CardInfo.ino, libraries/SD/examples/Datalogger/Datalogger.ino, libraries/SD/examples/DumpFile/DumpFile.ino, libraries/SD/examples/Files/Files.ino, libraries/SD/examples/ReadWrite/ReadWrite.ino, libraries/SD/examples/listfiles/listfiles.ino, libraries/SD/keywords.txt, libraries/SD/library.properties, libraries/SD/src/SD.cpp, libraries/SD/src/SD.h
Rebase library from version 1.05 to 1.06
Fixes issue with passing String class object to SD.exists()
=> ATLEDGE-393 Update SD library

libraries/Servo/Servo.cpp
JIRA: ATLEDGE-457
Servo.cpp warning
=> Fixed comparison between uint32 and int32

cores/arduino/stdlib_noniso.cpp
=> dtostrf: fix overflow problem

libraries/CurieTimerOne/CurieTimer.h
@bigdinotech @kmsywula Corrected typo error.  Please check.
=> Jira-500:  pwdStop should be pwmStop, typo error.

libraries/CurieEEPROM/examples/eeprom_write/eeprom_write.ino
-increment eeprom address at the correct location so it matches the read
example
=> CurieEEPROM eeprom_write example

platform.txt
Signed-off-by: Brian Baltz <brian.a.baltz@intel.com>
=> Use Go-based upload script

cores/arduino/wiring_digital.c
Check that pin number is not out of range in digitalRead(), digitalWrite() and pinMode()
=> check pin range first thing in pinMode(), digitalWrite() and digitalRead()

README.md
Break long lines to be <= 80 chars, where possible, and
add a new section to guide users to the appropriate place
for support (Arduino forum for product support, issue
tracker for bugs & features).
=> README.md: clean up and add "support" section

cores/arduino/Print.cpp, cores/arduino/Print.h
-fixes some issues with printing float and double
-limits the number of decimal places printable to 16
=> Fix some issues with printing float and double

cores/arduino/Print.cpp, cores/arduino/Print.h
This reverts commit b8ea343bb237762de6ee3a60ba0b1e8d5af12ff0.
The bug that was originally being fixed turns out to not be a bug at all.
Additionally this change caused some stability issues
=> Revert "Fix some issues with printing float and double"

platform.txt
=> Add -std=gnu11 to compiler.c.flags in platform.txt

README.md
@calvinatintel  @bigdinotech  review please
=> README.md: add "commit message how-to" wiki link

platform.txt
Signed-off-by: Brian Baltz <brian.a.baltz@intel.com>
=> Verify BLE FW version on every sketch upload

libraries/CurieMailbox/CurieMailbox.cpp, libraries/CurieMailbox/CurieMailbox.h, libraries/CurieMailbox/CurieMailboxMsg.h, libraries/CurieMailbox/README.txt, libraries/CurieMailbox/examples/SharedCounter/SharedCounter.ino, libraries/CurieMailbox/examples/String/String.ino, libraries/CurieMailbox/keywords.txt, libraries/CurieMailbox/library.properties
Zephyr sample applications to go with the example sketches
can be found in CODK-M-X86-Samples
(Followed on from #277)
=> Add CurieMailbox library

platform.txt
Update expected BLE version with one found in V3 image.
Update the corelibs version to 2.0.0
=> Update expected BLE version for V3

system/libarc32_arduino101/framework/include/platform.h
-reduce the buffer size used for the Shared Memory Communication library
=> reduce sahred memory buffer size

libraries/CurieBLE/examples/BatteryAdvChange/BatteryAdvChange.ino, libraries/CurieBLE/examples/BatteryMonitor/BatteryMonitor.ino, libraries/CurieBLE/examples/ButtonLED/ButtonLED.ino, libraries/CurieBLE/examples/CallbackLED/CallbackLED.ino, libraries/CurieBLE/examples/IMUBleCentral/IMUBleCentral.ino, libraries/CurieBLE/examples/IMUBleNotification/IMUBleNotification.ino, libraries/CurieBLE/examples/LED/LED.ino, libraries/CurieBLE/examples/LEDCentral/LEDCentral.ino, libraries/CurieBLE/examples/Scanning/Scanning.ino, libraries/CurieBLE/examples/UpdateConnectionInterval/UpdateConnectionInterval.ino
@noelpaz , Noel please review these changes. No logic change just corrected spelling and grammar.  Changed such that associated sketches and/or apps are stated very clearly.
=> JIRA-685, Peripheral sketches shall state associated Central sketch.

cores/arduino/WString.cpp, cores/arduino/stdlib_noniso.cpp
I missed a couple of corner cases in my first implementation, which have
now been addressed. First reported in isssue #300.
@bigdinotech @calvinatintel @SidLeung @noelpaz @russmcinnis  please review
**Please do not merge until explicitly requested**
=> Fix dtostrf rounding strategy

platform.txt
in response to https://github.com/01org/corelibs-arduino101/issues/309
=> Use our own version of copy.exe so that we can copy without cmd.exe

README.md
@calvinatintel @bigdinotech @SidLeung please review
=> README.md: add link to ICS for product support

README.md
=> README.md: add steps for updating intel-arduino-tools

libraries/CurieBLE/examples/central/BatteryMonitor_Central/BatteryMonitor_Central.ino, libraries/CurieBLE/examples/central/sensortag_button/sensortag_button.ino, libraries/CurieBLE/examples/peripheral/BatteryMonitor_Notification/BatteryMonitor_Notification.ino, libraries/CurieBLE/examples/peripheral/MIDIBLE/MIDIBLE.ino
=> Modified SensorTag example and added some examples derived from 1.0.7

libraries/CurieBLE/examples/peripheral/MIDIBLE/MIDIBLE.ino
@russmcinnis @calvinatintel . Please review
The way to test this without Garageband or MacOS is to subscribed to the one characteristic and you should see it updating fast.
I will run BAT on this.
The  internal JSON to use is 157
=> Corrected the MIDIBLE example so it advertises correctly

libraries/CurieBLE/examples/test/CallbackLED/CallbackLED.ino, libraries/CurieBLE/examples/test/CommunitySketches/Genuino101CurieBLEHeartRateMonitor/Genuino101CurieBLEHeartRateMonitor.ino, libraries/CurieBLE/examples/test/CommunitySketches/StandardFirmataBLE/BLEStream.h, libraries/CurieBLE/examples/test/CommunitySketches/StandardFirmataBLE/StandardFirmataBLE.ino, libraries/CurieBLE/examples/test/CommunitySketches/StandardFirmataBLE/bleConfig.h, libraries/CurieBLE/examples/test/discoveratperipheral/discoveratperipheral.ino, libraries/CurieBLE/examples/test/profileatcentral/profileatcentral.ino
@SidLeung Adding test directory back to main trunk. Please review it.
=> Add test directory for CurieBLE examples

libraries/CurieBLE/examples/test/connupdateperipheral/connupdateperipheral.ino, libraries/CurieBLE/src/BLEDevice.cpp, libraries/CurieBLE/src/BLEDevice.h, libraries/CurieBLE/src/internal/BLEDeviceManager.cpp, libraries/CurieBLE/src/internal/BLEDeviceManager.h
Description:
This feature enables a sketch to change the Connection
Interval, Timeout, and Latency.  The feature is applicable
to both Central and Peripheral mode.  A change in the
interval in the midst of a connection will terminate
the connection.  A re-connection is required.
File mods:
1. BLEDeviceManager.cpp:
- Application facing Connection Interval updating APIs.
2. BLEDevice.cpp:
- The execution of the interval changing command.
File addition:
1. connupdateperipheral.ino:
- A demo sketch to show how a peripheral can change the
Connection Interval.
=> Jira 671, Support Connection Interval updating.

platform.txt
PR is created by cherry-picking https://github.com/01org/corelibs-arduino101/pull/521
=> Fix compile rules for paths with spaces

platform.txt
=> Update core version to 2.0.2
